---
linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/atomicptr/crab
  golint:
    min-confidence: 0.8
  lll:
    line-length: 120
  maligned:
    suggest-new: true
  misspell:
    locale: US

run:
  timeout: 5m

issues:
  max-same-issues: 0
  exclude-use-default: false
  exclude-dirs:
    - test
