builds:
- main: ./cmd/crab/main.go
  ldflags:
    - -w -extldflags "-static"
    - -X github.com/atomicptr/crab/pkg/meta.Version={{.Version}}
    - -X github.com/atomicptr/crab/pkg/meta.GitCommit={{.FullCommit}}
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
# Release
## Github Releases
release:
  github:
    owner: atomicptr
    name: crab
  draft: false
## Snap
snapcrafts:
  - name: crab
    publish: true
    summary: A versatile tool to crawl dozens of URLs from a given source.
    description: |
      A versatile tool to crawl dozens of URLs from a given source, like a sitemap or an URL list.
    grade: stable
    confinement: strict
    license: MIT
    base: core18
    apps:
      crab:
        plugs: ["network"]
## Homebrew
brews:
  - name: crab
    github:
      owner: atomicptr
      name: homebrew-tools
    folder: Formula
    homepage: "https://github.com/atomicptr/crab"
    description: |
      A versatile tool to crawl dozens of URLs from a given source, like a sitemap or an URL list.
## Scoop
scoop:
  bucket:
    owner: atomicptr
    name: scoop-bucket
  homepage: "https://github.com/atomicptr/crab"
  description: |
    A versatile tool to crawl dozens of URLs from a given source, like a sitemap or an URL list.
  license: MIT
## Docker
dockers:
  - dockerfile: Dockerfile
    image_templates:
      - "atomicptr/crab:latest"
      - "atomicptr/crab:{{.Tag}}"
      - "atomicptr/crab:v{{.Major}}"
      - "atomicptr/crab:v{{.Major}}.{{.Minor}}"