version: 2

builds:
- main: ./cmd/crab/main.go
  ldflags:
    - -w -extldflags "-static"
    - -X github.com/atomicptr/crab/pkg/meta.Version={{.Version}}
    - -X github.com/atomicptr/crab/pkg/meta.GitCommit={{.FullCommit}}
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
archives:
  - id: default
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

# Release

## Github Releases
release:
  github:
    owner: atomicptr
    name: crab
  draft: false


## AUR
aurs:
  - name: crab-bin
    homepage: &homepage "https://github.com/atomicptr/crab"
    description: &description |
      A versatile tool to crawl dozens of URLs from a given source, like a sitemap or an URL list.
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/crab-bin.git"
    provides:
      - tmplr
    commit_author:
      name: Christopher Kaster
      email: me@atomicptr.de
    maintainers: &maintainers
      - &maintainer "Christopher Kaster <me@atomicptr.de>"
    license: &license MIT

## Homebrew
brews:
  - name: crab
    repository:
      owner: atomicptr
      name: homebrew-tools
    directory: Formula
    homepage: *homepage
    description: *description

## Scoop
scoops:
  - name: crab
    repository:
      owner: atomicptr
      name: scoop-bucket
    homepage: *homepage
    description: *description
    license: *license

## Docker
dockers:
  - dockerfile: Dockerfile
    image_templates:
      - "atomicptr/crab:latest"
      - "atomicptr/crab:v{{.Major}}"
      - "atomicptr/crab:v{{.Major}}.{{.Minor}}"
      - "atomicptr/crab:{{.Tag}}"

## NFPM (deb and rpm)
nfpms:
  - package_name: crab
    vendor: atomicptr
    maintainer: *maintainer
    homepage: *homepage
    description: *description
    license: MIT
    formats:
      - deb
      - rpm
