language: go
addons:
  apt:
    packages:
      - snapcraft
env:
  global:
    - secure: RFRhKtSrbXyxoy3TzP9ZIwyCv2S+rNapsZyK0IgyQHuoRrUuXUN/Q5VMMja2PSoG7Ko8HXRnSOgWESIbV1lktt/6kaLHzKUiqFB5QWGnzoKi2elXDZNkMJXSj9ouqs9lC2zp1hovLJxzSdj0Igpr34YuQ3iEXodkjwHNodqzPQNMSvTy/L1Y1ZCYKc47UTDuuLAaz4lzUAgsDsbQwHiCAh+Lb/GhTrnAJaT/mVpCxvJlSy9BdJarooTJ9PekvBxuodLavqHUw/MUYfFi3JUlNottIIEVs1Q9aute6XrGxphgfQn7mEZlbWfszbzhSZkBcQN4dA3rFYj01nSW5UP5WhmytOoprcgbaxQasfA4I+V/fgJfJGKHbOlqoGw5Vklt9xu5UolSAyF0UGxdgytqccDZsmlbmL3xf6xkkZLe4g0Aa+QfGyU540Ev8vS3gnABcb1mSvtOuryu3bwYWpMn9OxdpzhXP556k1AayG2uRrXaA9IiGC9u5X0sdIHEIHZ43oIfF5eRzb6E1DAMfCsGUDWWnI2NdP2QEBC2rlDA6fWhT8+ghGVrWrRuGTGDe+iunHtkkUOwlxUWLEWFjg6XKryKsdCI2A8m5pP9rVWvp8X7uR3J1SBO0RLywf8ZdPGEBNPpj19tiuNE5GCuK9mryKlM7PiVkZgoBAalk0y5pss=
    - secure: SJRSUHAaOjbzMGgzVut1FDZPXkr4ni4ey2KA9TsSKhndwIHQr9bsM4kuPrUHsYEH3ONzoFmlzODJDHUXWa9c2mGfzXqW65Vu0Skug9dSXen6KcM+SglVHoQrc8P/MDmMsrQ3O1+Y8Kfh9ntBibSwanDKEW25KTWgCOGYz7vc7B5LLwRPCMputZLN1A8uuFQ2Gir79CFNBEDdleaw67Fu2K0u4ZXMlu8r70VX5g8X6+mrpp5cY6/puWhxOgEmvQRptr6FUaeTCbGxTTlurSjGIGe8QtZazwmb//p1ewIQNdk4WoWSg9UjNCmQZbBjPKizwbAUeVYksosoICIaB8KE3Aizes8F/EQdjZn7G4VZ0YbizhjUUYlRDhAILJywYv3fVrBUDXqFcc7BgJNQFM0/o7aJ0jnA1QgTscGZP+6Vtn8VDX2fKWwDcHRDPfiREjo2HDtSdQYG7DroeBy8oxn9uSSwc6RpqRCA3mS7ii2wGlIKZAK0NDnt+WC31CuvR/iWqrcmBIxISuI/xIP5tNoWF5OU6flVCaWxpi0QcINqsBO7fd05uIwN065X4zEmewAJLjbB2xn/sR5YNO4unh5vN8OyIRtkD8aJNdYAl+Whkd11+uNy11g0DABTDBNlhjESW8D338msdcSsReEXvKF/c25DXNJoGgTU8uKIeTNWSW0=
go:
  - '1.15'
before_script:
  - go get -u github.com/mattn/goveralls
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
before_install:
  - openssl aes-256-cbc -K $encrypted_7ebe6f038385_key -iv $encrypted_7ebe6f038385_iv
    -in snap.login.enc -out snap.login -d
script:
  - make build
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - "$(go env GOPATH)/bin/golangci-lint run"
  - "$(go env GOPATH)/bin/goveralls -coverprofile=coverage.out -service=travis-ci"
after_success:
  # reset go.mod/go.sum back to their initial state (after being modified by go get -u)
  - git checkout -- go.mod go.sum
  # login to snapcraft
  - test -n "$TRAVIS_TAG" && snapcraft login --with snap.login
  # login to Docker Hub
  - test -n "$TRAVIS_TAG" && docker login -u=atomicptr -p="$DOCKER_PASSWORD"
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
