language: go
addons:
  apt:
    packages:
      - snapcraft
env:
  global:
    secure: RFRhKtSrbXyxoy3TzP9ZIwyCv2S+rNapsZyK0IgyQHuoRrUuXUN/Q5VMMja2PSoG7Ko8HXRnSOgWESIbV1lktt/6kaLHzKUiqFB5QWGnzoKi2elXDZNkMJXSj9ouqs9lC2zp1hovLJxzSdj0Igpr34YuQ3iEXodkjwHNodqzPQNMSvTy/L1Y1ZCYKc47UTDuuLAaz4lzUAgsDsbQwHiCAh+Lb/GhTrnAJaT/mVpCxvJlSy9BdJarooTJ9PekvBxuodLavqHUw/MUYfFi3JUlNottIIEVs1Q9aute6XrGxphgfQn7mEZlbWfszbzhSZkBcQN4dA3rFYj01nSW5UP5WhmytOoprcgbaxQasfA4I+V/fgJfJGKHbOlqoGw5Vklt9xu5UolSAyF0UGxdgytqccDZsmlbmL3xf6xkkZLe4g0Aa+QfGyU540Ev8vS3gnABcb1mSvtOuryu3bwYWpMn9OxdpzhXP556k1AayG2uRrXaA9IiGC9u5X0sdIHEIHZ43oIfF5eRzb6E1DAMfCsGUDWWnI2NdP2QEBC2rlDA6fWhT8+ghGVrWrRuGTGDe+iunHtkkUOwlxUWLEWFjg6XKryKsdCI2A8m5pP9rVWvp8X7uR3J1SBO0RLywf8ZdPGEBNPpj19tiuNE5GCuK9mryKlM7PiVkZgoBAalk0y5pss=
go:
  - '1.14'
before_script:
  - go get -u github.com/mattn/goveralls
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
before_install:
  - openssl aes-256-cbc -K $encrypted_7ebe6f038385_key -iv $encrypted_7ebe6f038385_iv
    -in snap.login.enc -out snap.login -d
script:
  - make build
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - "$(go env GOPATH)/bin/golangci-lint run"
  - "$(go env GOPATH)/bin/goveralls -coverprofile=coverage.out -service=travis-ci"
after_success:
  # login to snapcraft
  - test -n "$TRAVIS_TAG" && snapcraft login --with snap.login
deploy:
  - provider: script
    skip_cleanup: true
    script: |
      env \
        GIT_COMMIT=$(git rev-list -1 HEAD) \
        GIT_VERSION=$(git --no-pager tag --points-at HEAD | head -n 1) \
        curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
