on:
  push:
    tags:
      - '*'
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: write

jobs:
  tests:
    name: CI Tests & Release
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.25'
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Install Dependencies
        run: |
          go install github.com/mattn/goveralls@latest
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.4.0
      - name: Build & Test
        run: |
          make build
          go test -v -covermode=count -coverprofile=coverage.out ./...
          $(go env GOPATH)/bin/golangci-lint run ./...
      - name: Goveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: coverage.out
      - name: Release Prep
        run: |
          git checkout -- go.mod go.sum
          docker login -u=atomicptr -p="$DOCKER_ACCESS_TOKEN"
        env:
          DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      - name: Release
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          AUR_KEY: ${{ secrets.AUR_KEY }}
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
